###############################################################################
# Copyright (c) 2011, 2013 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
#showSuccess:
#  customize:
#    communityTopicLogger:
#      template: [dsl_common, communityTopicLogger]
#      parts: [formCommunityTopicComment]
#      target: [before]
#      is_component: true

#    focusTopicComment:
#      template: [dsl_common, focusTopicComment]
#      parts: [formCommunityTopicComment]
#      target: [before]
#      is_component: false

#newSuccess:
#  customize:
#    communityNameDisplay:
#      template: [dsl_common, addCommunityName4NewTopic]
#      parts: [formCommunityTopic]
#      target: [before]
#      is_component: true

#createSuccess:
#  customize:
#    communityNameDisplay:
#      template: [dsl_common, addCommunityName4NewTopic]
#      parts: [formCommunityTopic]
#      target: [before]
#      is_component: true
      