###############################################################################
# Copyright (c) 2011, 2014 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
all:
  stylesheets: [/opDSLCommonPlugin/css/dsl_common.css, /opMICGadgetsPlugin/css/gadgets.css]

smtMembersSuccess:
  layout: smtLayoutSns
