<?php

/**
 * PluginCommunityTopicPdfTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginCommunityTopicPdfTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginCommunityTopicPdfTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginCommunityTopicPdf');
    }
}