###############################################################################
# Copyright (c) 2011, 2013 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
options:
  charset: utf8

PageLog:
  actAs: [Timestampable]
  columns:
    member_id: { type: integer(4), notnull: true }
    url:      { type: string, notnull: true }
    client_epoc: {type: integer(5), notnull:true }
    event:    { type: string, notnull: true}
  relations:
    Member: { local: member_id,  foreign: id, onDelete: cascade }

ElementLog:
  actAs: [Timestampable]
  columns:
    member_id: { type: integer(4), notnull: true }
    url:      { type: string, notnull: true }
    client_epoc: {type: integer(5), notnull:true }
    selector:  { type: string, notnull: true }
    event:    {type: string, notnull: true}
    props: {type: string, notnull: false}
  relations:
    Member: {local: member_id,  foreign: id, onDelete: cascade }
