###############################################################################
# Copyright (c) 2011, 2013 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
default:
  stylesheets:    [/opSkinBasicPlugin/css/main.css, /opDSLCommonPlugin/css/dsl_common.css, /opSkinMICPlugin/css/mic.css]
  javascripts:    [jquery.min.js, op_activity.js]
