###############################################################################
# Copyright (c) 2011, 2014 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
options:
  charset: utf8

CommunityTopicPdf:
  columns:
    id: {type integer(4), primary: true, autoincrement: true}
    post_id: { type: integer(4), notnull: true }
    file_id: { type: integer(4), notnull: true }
  relations:
    CommunityTopic: { local: post_id,  foreign: id, onDelete: cascade }
    File: { local: file_id, foreign: id, onDelete: cascade }
