<?php

/**
 * PluginElementLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginElementLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginElementLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginElementLog');
    }
}