<?php

/**
 * PluginPageLogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginPageLogTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginPageLogTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginPageLog');
    }
}