###############################################################################
# Copyright (c) 2011, 2014 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
extping_community_members:
  url: /e_ping/listCommunityMembers/:id
  class: sfDoctrineRoute
  param: {module: ping, action: listCommunityMembers}
  requirements:
    id: \d+
    sf_method: [get]
  options: { model: Community, type: object }
