###############################################################################
# Copyright (c) 2011, 2013 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
dslTakePicture:
  caption:
    ja_JP: "写真を撮る"
  description:
    ja_JP: "写真鳥がジェット"
  component: [dslcam, takePicture]

dslEventGrid:
  caption:
    ja_JP: "イベント一覧"
  description:
    ja_JP: "自分にかかわるイベント一覧"
  component: [dslevent, myEventGrid]

dslHomeMenu:
  caption:
    ja_JP: "アクションメニュー"
  description:
    ja_JP: "アクションメニュー"
  component: [dslmenu, homeMenu]

dslOverrideInformationBox:
  caption:
    ja_JP: "InformationBoxスタイル変更"
  description:
    ja_JP: "InformationBoxのスタイルを変更"
  component: [dslstyle, overrideInformationBox]

dslOverrideComments:
  caption:
    ja_JP: "Commentsスタイル変更"
  description:
    ja_JP: "Commentのスタイルを変更"
  component: [dslstyle, overrideComments]
