###############################################################################
# Copyright (c) 2011, 2014 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
dslTakePicture:
  caption:
    ja_JP: "写真を撮る"
  description:
    ja_JP: "写真鳥がジェット"
  component: [dslcam, takePicture]

dslEventGrid:
  caption:
    ja_JP: "イベント一覧"
  description:
    ja_JP: "自分にかかわるイベント一覧"
  component: [dslevent, myEventGrid]
  config:
    cells:
      Name:      "cells"
      Caption:   "表示セル数"
      FormType:  "select"
      ValueType:  "int"
      IsRequired: true
      Default:    5
      Choices:
        3: 3
        5: 5
        7: 7
    rows:
      Name:      "rows"
      Caption:   "表示行数"
      FormType:  "radio"
      ValueType:  "int"
      IsRequired: true
      Default:    1
      Choices:
        1: "一行"
        2: "二行"
    order:
      Name:      "order"
      Caption:   "表示方向"
      FormType:  "radio"
      ValueType:  "text"
      IsRequired: true
      Default:    "horizontal"
      Choices:
        horizontal: "横方向"
        vertical: "縦方向"

dslHomeMenu:
  caption:
    ja_JP: "アクションメニュー"
  description:
    ja_JP: "アクションメニュー"
  component: [dslmenu, homeMenu]

dslOverrideInformationBox:
  caption:
    ja_JP: "InformationBoxスタイル変更"
  description:
    ja_JP: "InformationBoxのスタイルを変更"
  component: [dslstyle, overrideInformationBox]

dslOverrideComments:
  caption:
    ja_JP: "Commentsスタイル変更"
  description:
    ja_JP: "Commentのスタイルを変更"
  component: [dslstyle, overrideComments]

dslOverrideTimeline:
  caption:
    ja_JP: "Timeline見た目変更"
  description:
    ja_JP: "Timeline内の用語、スタイル変更、Youtube埋め込み"
  component: [dslstyle, overrideTimeline]
